### ISSUE TITLE
请问jellyfin怎么使用？

### ISSUE THREAD

**Issue by NikoYomi** [newday-life/jellyfin-crx#1]
请问jellyfin怎么使用？

**Comment by newday-life** [comment]
Chrome 扩展设置 > 开发者模式 > 加载已解压的扩展程序 > 直接选择源码即可

**Comment by NikoYomi** [comment]
> Chrome 扩展设置 > 开发者模式 > 加载已解压的扩展程序 > 直接选择源码即可

请问怎么在docker中使用呢？就是安装在服务器上

**Comment by newday-life** [comment]
> > Chrome 扩展设置 > 开发者模式 > 加载已解压的扩展程序 > 直接选择源码即可
> 
> 请问怎么在docker中使用呢？就是安装在服务器上

我不知道！你可以参考别人教程：https://mj.tk/2023/07/Emby   在Jellyfin也是差不多。
