### ISSUE TITLE
当媒体库数量较多时，超过首页显示的6个媒体库时，第七个媒体库图片出现一半然后突然消失

### ISSUE THREAD

**Issue by Hovenia** [newday-life/jellyfin-crx#11]
![Uploading 1.png…]()
![Uploading 2.jpg…]()

**Comment by newday-life** [comment]
![image](https://github.com/newday-life/jellyfin-crx/assets/25839463/8e9c47e0-95c9-4b59-903c-4dbeffe9e862)
人问题，有种操作叫左右导航切换。

**Comment by Hovenia** [comment]
> ![image](https://user-images.githubusercontent.com/25839463/282291759-8e9c47e0-95c9-4b59-903c-4dbeffe9e862.png) 人问题，有种操作叫左右导航切换。

这个我知道啊，我说的是刚入进入时的过渡动画，开始会加载第七个媒体库，但是过渡动画加载完会这个媒体库突然消失，很突兀，emby-crx上面没有这个问题

**Comment by newday-life** [comment]
那你提个pr，或者用emby-crx就好了

**Comment by newday-life** [comment]
jellyfin webUI本身设计就是隐藏溢出屏幕的卡片的，加了卡片显示动画，导致隐藏过程被感知，要么全都不要动画，要么就不隐藏溢出屏幕的卡片（这样整体风格不统一），想要自己DIY吧。
