### ISSUE TITLE
更新精简代码后.在手机端这个无法划动

### ISSUE THREAD

**Issue by hh0610** [newday-life/jellyfin-crx#12]
![11](https://github.com/newday-life/jellyfin-crx/assets/142991330/f4e24105-e71e-4525-9f5a-9416563076d0)

**Comment by jackloves111** [comment]
实测，是safari的浏览器无法滑动，换edge就可以了，应该是改了什么东西导致不兼容苹果浏览器了，我苹果手机13实测，会遮挡住
![6a9d3963-b768-410b-a027-b175a87bdf05](https://github.com/newday-life/jellyfin-crx/assets/89971817/a687203e-a279-4a3a-b8cf-4788ddc9553a)

**Comment by hh0610** [comment]
> 实测，是safari的浏览器无法滑动，换edge就可以了，应该是改了什么东西导致不兼容苹果浏览器了，我苹果手机13实测，会遮挡住 ![6a9d3963-b768-410b-a027-b175a87bdf05](https://user-images.githubusercontent.com/89971817/282442543-a687203e-a279-4a3a-b8cf-4788ddc9553a.png)

安卓手机也一样的

**Comment by hh0610** [comment]
> 实测，是safari的浏览器无法滑动，换edge就可以了，应该是改了什么东西导致不兼容苹果浏览器了，我苹果手机13实测，会遮挡住 ![6a9d3963-b768-410b-a027-b175a87bdf05](https://user-images.githubusercontent.com/89971817/282442543-a687203e-a279-4a3a-b8cf-4788ddc9553a.png)

安卓手机媒体库无法滑动

**Comment by jackloves111** [comment]
好像是的，我用浏览器模拟手机，无法滑动了，可能之前是缓存，所以可以滑动

**Comment by newday-life** [comment]
针对 #11 的问题加了一个css导致触控设备无法滑动已修复
