### ISSUE TITLE
iPhone13  页面文字被遮挡，浏览器模拟的正常

### ISSUE THREAD

**Issue by jackloves111** [newday-life/jellyfin-crx#14]
![7392ef8b-f1de-450e-9bac-bec29952012b](https://github.com/newday-life/jellyfin-crx/assets/89971817/84ca03f3-4e8b-43b1-a457-4e1cac8353ea)

**Comment by newday-life** [comment]
这是什么浏览器啊？

**Comment by newday-life** [comment]
![photo_2023-11-14_01-25-02](https://github.com/newday-life/jellyfin-crx/assets/25839463/02e4eea9-f571-42e9-8dab-1ef0c0df59b1)
![photo_2023-11-14_01-25-16](https://github.com/newday-life/jellyfin-crx/assets/25839463/bdb9eddb-aa6b-402f-995a-5b405ded8bcf)
我这边在safari浏览器和app jellyfin 都正常

**Comment by jackloves111** [comment]
现在正常了，可能是缓存问题
