### ISSUE TITLE
安装完jellyfin没有变化

### ISSUE THREAD

**Issue by hh0610** [newday-life/jellyfin-crx#9]
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:01:09--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/script.sh
Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2459 (2.4K) [text/plain]
Saving to: 'script.sh'

script.sh           100%[===================>]   2.40K  2.79KB/s    in 0.9s

2023-11-09 18:01:12 (2.79 KB/s) - 'script.sh' saved [2459/2459]

请输入 Jellyfin 容器名称:jellyfin
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:01:24--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/css/style.css
Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9966 (9.7K) [text/plain]
Saving to: 'style.css'

style.css           100%[===================>]   9.73K  3.53KB/s    in 2.8s

2023-11-09 18:01:30 (3.53 KB/s) - 'style.css' saved [9966/9966]

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:01:30--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/common-utils.js
Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1459 (1.4K) [text/plain]
Saving to: 'common-utils.js'

common-utils.js     100%[===================>]   1.42K  1.58KB/s    in 0.9s

2023-11-09 18:01:35 (1.58 KB/s) - 'common-utils.js' saved [1459/1459]

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:01:35--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/jquery-3.6.0.min.js
Resolving raw.githubusercontent.com... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 89501 (87K) [text/plain]
Saving to: 'jquery-3.6.0.min.js'

jquery-3.6.0.min.js 100%[===================>]  87.40K  2.58KB/s    in 34s

2023-11-09 18:02:13 (2.58 KB/s) - 'jquery-3.6.0.min.js' saved [89501/89501]

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:02:13--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/md5.min.js
Resolving raw.githubusercontent.com... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3992 (3.9K) [text/plain]
Saving to: 'md5.min.js'

md5.min.js          100%[===================>]   3.90K  1.15KB/s    in 3.4s

2023-11-09 18:02:22 (1.15 KB/s) - 'md5.min.js' saved [3992/3992]

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2023-11-09 18:02:22--  https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/content/content/main.js
Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-09 18:02:28 ERROR 404: Not Found.

成功！Index.html 首次安装！

**Comment by newday-life** [comment]
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:09-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/script.sh Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 2459 (2.4K) [text/plain] Saving to: 'script.sh'
> 
> script.sh 100%[===================>] 2.40K 2.79KB/s in 0.9s
> 
> 2023-11-09 18:01:12 (2.79 KB/s) - 'script.sh' saved [2459/2459]
> 
> 请输入 Jellyfin 容器名称:jellyfin Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:24-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/css/style.css Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 9966 (9.7K) [text/plain] Saving to: 'style.css'
> 
> style.css 100%[===================>] 9.73K 3.53KB/s in 2.8s
> 
> 2023-11-09 18:01:30 (3.53 KB/s) - 'style.css' saved [9966/9966]
> 
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:30-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/common-utils.js Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 1459 (1.4K) [text/plain] Saving to: 'common-utils.js'
> 
> common-utils.js 100%[===================>] 1.42K 1.58KB/s in 0.9s
> 
> 2023-11-09 18:01:35 (1.58 KB/s) - 'common-utils.js' saved [1459/1459]
> 
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:35-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/jquery-3.6.0.min.js Resolving raw.githubusercontent.com... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8001::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 89501 (87K) [text/plain] Saving to: 'jquery-3.6.0.min.js'
> 
> jquery-3.6.0.min.js 100%[===================>] 87.40K 2.58KB/s in 34s
> 
> 2023-11-09 18:02:13 (2.58 KB/s) - 'jquery-3.6.0.min.js' saved [89501/89501]
> 
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:13-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/md5.min.js Resolving raw.githubusercontent.com... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8000::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 3992 (3.9K) [text/plain] Saving to: 'md5.min.js'
> 
> md5.min.js 100%[===================>] 3.90K 1.15KB/s in 3.4s
> 
> 2023-11-09 18:02:22 (1.15 KB/s) - 'md5.min.js' saved [3992/3992]
> 
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:22-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/content/content/main.js Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 404 Not Found 2023-11-09 18:02:28 ERROR 404: Not Found.
> 
> 成功！Index.html 首次安装！

main.js地址错误，已修正可以再试一下

**Comment by jackloves111** [comment]
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:09-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/script.sh Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 2459 (2.4K) [text/plain] Saving to: 'script.sh'
> > script.sh 100%[===================>] 2.40K 2.79KB/s in 0.9s
> > 2023-11-09 18:01:12 (2.79 KB/s) - 'script.sh' saved [2459/2459]
> > 请输入 Jellyfin 容器名称:jellyfin Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:24-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/css/style.css Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 9966 (9.7K) [text/plain] Saving to: 'style.css'
> > style.css 100%[===================>] 9.73K 3.53KB/s in 2.8s
> > 2023-11-09 18:01:30 (3.53 KB/s) - 'style.css' saved [9966/9966]
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:30-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/common-utils.js Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 1459 (1.4K) [text/plain] Saving to: 'common-utils.js'
> > common-utils.js 100%[===================>] 1.42K 1.58KB/s in 0.9s
> > 2023-11-09 18:01:35 (1.58 KB/s) - 'common-utils.js' saved [1459/1459]
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:35-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/jquery-3.6.0.min.js Resolving raw.githubusercontent.com... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8001::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 89501 (87K) [text/plain] Saving to: 'jquery-3.6.0.min.js'
> > jquery-3.6.0.min.js 100%[===================>] 87.40K 2.58KB/s in 34s
> > 2023-11-09 18:02:13 (2.58 KB/s) - 'jquery-3.6.0.min.js' saved [89501/89501]
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:13-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/md5.min.js Resolving raw.githubusercontent.com... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8000::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 3992 (3.9K) [text/plain] Saving to: 'md5.min.js'
> > md5.min.js 100%[===================>] 3.90K 1.15KB/s in 3.4s
> > 2023-11-09 18:02:22 (1.15 KB/s) - 'md5.min.js' saved [3992/3992]
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:22-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/content/content/main.js Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 404 Not Found 2023-11-09 18:02:28 ERROR 404: Not Found.
> > 成功！Index.html 首次安装！
> 
> main.js地址错误，已修正可以再试一下

不是地址问题，他的wget版本无法打开存储HSTS数据库的文件

**Comment by newday-life** [comment]
> > > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:09-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/script.sh Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 2459 (2.4K) [text/plain] Saving to: 'script.sh'
> > > script.sh 100%[===================>] 2.40K 2.79KB/s in 0.9s
> > > 2023-11-09 18:01:12 (2.79 KB/s) - 'script.sh' saved [2459/2459]
> > > 请输入 Jellyfin 容器名称:jellyfin Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:24-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/css/style.css Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 9966 (9.7K) [text/plain] Saving to: 'style.css'
> > > style.css 100%[===================>] 9.73K 3.53KB/s in 2.8s
> > > 2023-11-09 18:01:30 (3.53 KB/s) - 'style.css' saved [9966/9966]
> > > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:30-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/common-utils.js Resolving raw.githubusercontent.com... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8003::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 1459 (1.4K) [text/plain] Saving to: 'common-utils.js'
> > > common-utils.js 100%[===================>] 1.42K 1.58KB/s in 0.9s
> > > 2023-11-09 18:01:35 (1.58 KB/s) - 'common-utils.js' saved [1459/1459]
> > > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:01:35-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/jquery-3.6.0.min.js Resolving raw.githubusercontent.com... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8001::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 89501 (87K) [text/plain] Saving to: 'jquery-3.6.0.min.js'
> > > jquery-3.6.0.min.js 100%[===================>] 87.40K 2.58KB/s in 34s
> > > 2023-11-09 18:02:13 (2.58 KB/s) - 'jquery-3.6.0.min.js' saved [89501/89501]
> > > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:13-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/md5.min.js Resolving raw.githubusercontent.com... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8000::154|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 3992 (3.9K) [text/plain] Saving to: 'md5.min.js'
> > > md5.min.js 100%[===================>] 3.90K 1.15KB/s in 3.4s
> > > 2023-11-09 18:02:22 (1.15 KB/s) - 'md5.min.js' saved [3992/3992]
> > > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2023-11-09 18:02:22-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/content/content/main.js Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected. HTTP request sent, awaiting response... 404 Not Found 2023-11-09 18:02:28 ERROR 404: Not Found.
> > > 成功！Index.html 首次安装！
> > 
> > 
> > main.js地址错误，已修正可以再试一下
> 
> 不是地址问题，他的wget版本无法打开存储HSTS数据库的文件

![image](https://github.com/newday-life/jellyfin-crx/assets/25839463/3738b708-f3e9-475a-a042-92264ccaa821)
难道没看出这地址多了一个“content”？

**Comment by hh0610** [comment]
> > > > 不适用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：01：09-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/script.sh 解决 raw.githubusercontent.com...2606：50c0：8003：：154， 2606：50c0：8001：：154， 2606：50c0：8000：：154， ...连接到 raw.githubusercontent.com|2606：50c0：8003：：154|：443...连接。HTTP 请求已发送，正在等待响应...200 OK 长度：2459 （2.4K） [text/plain] 保存到：“script.sh”script.sh 100%[=======================>] 2.40K 2.79KB/s 在 0.9s 内 2023-11-09 18：01：12 （2.79 KB/s） - “script.sh”已保存 [2459/2459] 请输入 Jellyfin 容器名称：jellyfin 不会应用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：01：24-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/css/style.css 解决 raw.githubusercontent.com...2606：50c0：8002：：154， 2606：50c0：8000：：154， 2606：50c0：8001：：154， ...正在连接到 raw.githubusercontent.com|2606：50c0：8002：：154|：443...连接。HTTP 请求已发送，正在等待响应...200 OK 长度：9966 （9.7K） [text/plain] 保存到：“style.css”样式.css 100%[=======================>] 9.73K 3.53KB/s 在 2.8s 内 2023-11-09 18：01：30 （3.53 KB/s） - “style.css”已保存 [9966/9966] 不适用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：01：30-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/common-utils.js 解决 raw.githubusercontent.com...2606：50c0：8003：：154， 2606：50c0：8002：：154， 2606：50c0：8000：：154， ...连接到 raw.githubusercontent.com|2606：50c0：8003：：154|：443...连接。HTTP 请求已发送，正在等待响应...200 OK 长度：1459 （1.4K） [text/plain] 保存到：“common-utils.js”，common-utils.js 100%[=====================>] 1.42K 1.58KB/s 在 0.9s 内 2023-11-09 18：01：35 （1.58 KB/s） - “common-utils.js”已保存 [1459/1459] 不会应用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：01：35-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/jquery-3.6.0.min.js 解决 raw.githubusercontent.com...2606：50c0：8001：：154， 2606：50c0：8003：：154， 2606：50c0：8002：：154， ...正在连接到 raw.githubusercontent.com|2606：50c0：8001：：154|：443...连接。HTTP 请求已发送，正在等待响应...200 OK 长度：89501 （87K） [text/plain] 保存到：“jquery-3.6.0.min.js”jquery-3.6.0.min.js 100%[=====================>] 87.40K 2.58KB/s 在 34s 内 2023-11-09 18：02：13 （2.58 KB/s） - “jquery-3.6.0.min.js”已保存 [89501/89501] 不会应用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：02：13-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/static/js/md5.min.js 解决 raw.githubusercontent.com...2606：50c0：8000：：154， 2606：50c0：8001：：154， 2606：50c0：8003：：154， ...正在连接到 raw.githubusercontent.com|2606：50c0：8000：：154|：443...康恩CTED的。HTTP 请求已发送，正在等待响应...200 OK 长度：3992 （3.9K） [text/plain] 保存到：“md5.min.js”md5.min.js 100%[=====================>] 3.90K 1.15KB/s 在 3.4s 2023-11-09 18：02：22 （1.15 KB/s） - “md5.min.js”已保存 [3992/3992] 不会应用 HSTS。HSTS 数据库必须是常规的、不可全局写入的文件。错误：无法在“/root/.wget-hsts”中打开 HSTS 存储。HSTS 将被禁用。--2023-11-09 18：02：22-- https://raw.githubusercontent.com/newday-life/jellyfin-crx/master/content/content/main.js 解决 raw.githubusercontent.com...2606：50c0：8002：：154， 2606：50c0：8000：：154， 2606：50c0：8001：：154， ...正在连接到 raw.githubusercontent.com|2606：50c0：8002：：154|：443...连接。HTTP 请求已发送，正在等待响应...404 未找到 2023-11-09 18：02：28 错误 404：未找到。 成功！Index.html 首次安装！
> > > 
> > > 
> > > main.js地址错误，已修正可以再试一下
> > 
> > 
> > 不是地址问题，他的wget版本无法打开存储HSTS数据库的文件
> 
> ![图像](https://user-images.githubusercontent.com/25839463/281740337-3738b708-f3e9-475a-a042-92264ccaa821.png)难道没看出这地址多了一个“content”？

可以了.多谢了
